sudo: required
services:
  - docker

before_install:
  - docker build -t nreoch9/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run nreoch9/react-test npm test -- --coverage

after_success:
  # Build images
  - docker build -t nreoch9/multi-client ./client
  - docker build -t nreoch9/multi-nginx ./nginx
  - docker build -t nreoch9/multi-server ./server
  - docker build -t nreoch9/multi-worker ./worker
  # Login to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push images to docker hub
  - docker push nreoch9/multi-client
  - docker push nreoch9/multi-nginx
  - docker push nreoch9/multi-server
  - docker push nreoch9/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-container
  env: MultiContainer-env
  bucket_name: elasticbeanstalk-us-east-2-031556766649
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
